apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: order-vs
  namespace: testns
spec:
  hosts:
  - "LB URL"
  gateways:
  - order-gateway
  http:
  - route:
      - destination:
          host: order-svc
          port: 
            number: 8080
