apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
  labels:
    app: inventory
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
  - port: 8081
  selector:
    app: inventory
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-inventory
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: container-inventory
        image: rajeevjaiiswal/inventory:latest
        ports:
        - containerPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-newinvent
  labels:
    app: newinventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: container-newinventory
        image: rajeevjaiiswal/newinventory:latest
        ports:
        - containerPort: 8081

