apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
  labels:
    app: inventory
spec:
  clusterIP: None
  ports:
  - port: 8081
  selector:
    app: inventory
---

apiVersion: v1
kind: Service
metadata:
  name: inventory-svc-normal
  labels:
    app: inventory
spec:
  ports:
  - port: 8081
  selector:
    app: inventory
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  serviceName: "inventory-svc"
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: container-inventory
        image: rajeevjaiiswal/inventory:latest
        ports:
        - containerPort: 8081

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory1
  labels:
    app: newinventory
spec:
  serviceName: "inventory-svc"
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: container-newinventory
        image: rajeevjaiiswal/newinventory:latest
        ports:
        - containerPort: 8081

